namespace iChiba.ACC.CustomException
{
    public class ErrorCodeDefine : iChibaShopping.Core.CustomException.ErrorCodeDefine
    {
        public const string CHECK_BANK_ACCOUNT = "THE_BANK_ACCOUNT_ALREADY_EXISTS_IN_THE_SYSTEM";

        #region Deposit

        public const string EXIST_DEPOSIT_WAITING = "EXIST_DEPOSIT_WAITING";
        public const string DEPOSIT_AMOUNT_MUST_GT_MINIMUM_VALUE = "DEPOSIT_AMOUNT_MUST_GT_MINIMUM_VALUE";
        public const string DEPOSIT_BANK_NAME_MUST_INPUT = "DEPOSIT_BANK_NAME_MUST_INPUT";
        public const string DEPOSIT_BANK_NUMBER_MUST_INPUT = "DEPOSIT_BANK_NUMBER_MUST_INPUT";
        public const string DEPOSIT_WALLET_NOT_EXISTING = "DEPOSIT_WALLET_NOT_EXISTING";
        public const string DEPOSIT_DATA_CHANGED = "DEPOSIT_DATA_CHANGED";
        public const string DEPOSIT_DATA_NOTFOUND = "DEPOSIT_DATA_NOTFOUND";

        #endregion Deposit

        #region config export
        public const string EXPORT_MESSAGE = "DATA_EXPORT_NOTFOUND";
        #endregion

        #region Withdraw

        public const string EXIST_WITHDRAW_WAITING = "EXIST_WITHDRAW_WAITING";
        public const string WITHDRAW_AMOUNT_MUST_GT_MINIMUM_VALUE = "WITHDRAW_AMOUNT_MUST_GT_MINIMUM_VALUE";
        public const string WITHDRAW_BANK_NAME_MUST_INPUT = "WITHDRAW_BANK_NAME_MUST_INPUT";
        public const string WITHDRAW_ACCOUNT_NUMBER_MUST_INPUT = "WITHDRAW_ACCOUNT_NUMBER_MUST_INPUT";
        public const string WITHDRAW_ACCOUNT_NAME_MUST_INPUT = "WITHDRAW_ACCOUNT_NAME_MUST_INPUT";
        public const string WITHDRAW_BRANCH_MUST_INPUT = "WITHDRAW_BRANCH_MUST_INPUT";
        public const string WITHDRAW_PROVINCE_MUST_INPUT = "WITHDRAW_PROVINCE_MUST_INPUT";
        public const string WITHDRAW_WALLET_NOT_EXISTING = "WITHDRAW_WALLET_NOT_EXISTING";
        public const string WITHDRAW_YOUR_BALANCE_NOT_ENOUGH = "WITHDRAW_YOUR_BALANCE_NOT_ENOUGH";
        public const string WITHDRAW_DATA_CHANGED = "WITHDRAW_DATA_CHANGED";

        #endregion Withdraw

        #region orderbyforyou
        public const string CHECK_UPDATE_STATUS = "CAN'T UPDATE STATUS";
        public const string ORDER_DETAIL_STATUS_NOT_ALLOW = "ORDER_DETAIL_STATUS_NOT_ALLOW";

        #endregion

        public const string ORDER_STATUS_UPDATE_NOT_ALLOW = "ORDER_STATUS_UPDATE_NOT_ALLOW";
        public const string ORDER_GET_SHIPPING_FEE_ORDER_DETAIL_MULTI = "ORDER_GET_SHIPPING_FEE_ORDER_DETAIL_MULTI";
        public const string ORDER_GET_SHIPPING_FEE_JUST_SUPPORT_AUCTION = "ORDER_GET_SHIPPING_FEE_JUST_SUPPORT_AUCTION";

        public const string ORDER_GET_TRACKING_NUMBER_ORDER_DETAIL_MULTI = "ORDER_GET_TRACKING_NUMBER_ORDER_DETAIL_MULTI";
        public const string ORDER_GET_TRACKING_NUMBER_JUST_SUPPORT_AUCTION = "ORDER_GET_TRACKING_NUMBER_JUST_SUPPORT_AUCTION";
        public const string ORDER_GET_TRACKING_NUMBER_FAIL_OR_TRACKING_NUMBER_NOT_EXISTING = "ORDER_GET_TRACKING_NUMBER_FAIL_OR_TRACKING_NUMBER_NOT_EXISTING";
        public const string CANNOT_COMPLETE_THE_TRANSACTION = "CANNOT_COMPLETE_THE_TRANSACTION";

        public const string ORDER_SPLIT_NOT_MATCH_ORDER_DETAIL = "ORDER_SPLIT_NOT_MATCH_ORDER_DETAIL";
        public const string ORDER_DETAIL_SPLIT_QUANTITY_NOT_MATCH = "ORDER_DETAIL_SPLIT_QUANTITY_NOT_MATCH";
        public const string ORDER_SPLIT_QUANTITY_MUST_GT_0 = "ORDER_SPLIT_QUANTITY_MUST_GT_0";
        public const string ORDER_SPLIT_CANT_AUTO_APPROVE_WAIT_FOR_BUY_PRODUCT = "ORDER_SPLIT_CANT_AUTO_APPROVE_WAIT_FOR_BUY_PRODUCT";
        public const string ORDER_SPLIT_CANT_AUTO_APPROVE_BUY_PRODUCT = "ORDER_SPLIT_CANT_AUTO_APPROVE_BUY_PRODUCT";
        public const string ORDER_SPLIT_CANT_AUTO_CANCEL_ORDER_BY_FOR_YOU = "ORDER_SPLIT_CANT_AUTO_CANCEL_ORDER_BY_FOR_YOU";

        public const string ORDER_DETAIL_UPDATE_STATUS_CANT_AUTO_APPROVE_BUY_PRODUCT = "ORDER_DETAIL_UPDATE_STATUS_CANT_AUTO_APPROVE_BUY_PRODUCT";
        public const string ORDER_DETAIL_UPDATE_STATUS_CANT_AUTO_CANCEL_ORDER = "ORDER_DETAIL_UPDATE_STATUS_CANT_AUTO_CANCEL_ORDER";

        #region Freeze

        public const string FREEZE_WALLET_NOT_EXISTING = "FREEZE_WALLET_NOT_EXISTING";
        public const string FREEZE_TEMPORARY_DEPOSIT_VIP_EXISTING = "TEMPORARY_DEPOSIT_VIP_EXISTING";
        public const string FREEZE_TEMPORARY_DEPOSIT_VIP_YOUR_BALANCE_NOT_ENOUGH = "FREEZE_TEMPORARY_DEPOSIT_VIP_YOUR_BALANCE_NOT_ENOUGH";
        public const string FREEZE_TEMPORARY_DEPOSIT_NOT_EXISTING = "FREEZE_TEMPORARY_DEPOSIT_NOT_EXISTING";
        public const string FREEZE_DATA_CHANGED = "FREEZE_DATA_CHANGED";
        public const string FREEZE_PRODUCT_BIDDING_EXISTING = "FREEZE_PRODUCT_BIDDING_EXISTING";
        public const string FREEZE_PRODUCT_BID_LAST_TIME_EXISTING = "FREEZE_PRODUCT_BID_LAST_TIME_EXISTING";
        public const string FREEZE_PRODUCT_PRICE_INVALID = "FREEZE_PRODUCT_PRICE_INVALID";
        public const string FREEZE_TEMPORARY_DEPOSIT_PRODUCT_YOUR_BALANCE_NOT_ENOUGH = "FREEZE_TEMPORARY_DEPOSIT_PRODUCT_YOUR_BALANCE_NOT_ENOUGH";

        #endregion Freeze

        #region Payment

        public const string PAYMENT_WALLET_NOT_EXISTING = "PAYMENT_WALLET_NOT_EXISTING";
        public const string PAYMENT_REF_MUST_INPUT = "PAYMENT_REF_MUST_INPUT";
        public const string PAYMENT_AMOUNT_MUST_GT_MINIMUM_VALUE = "PAYMENT_AMOUNT_MUST_GT_MINIMUM_VALUE";
        public const string PAYMENT_YOUR_BALANCE_NOT_ENOUGH = "PAYMENT_YOUR_BALANCE_NOT_ENOUGH";
        public const string PAYMENT_CANCEL_EXISTING = "PAYMENT_CANCEL_EXISTING";
        public const string PAYMENT_EXISTING = "PAYMENT_EXISTING";
        public const string PAYMENT_DATA_CHANGED = "PAYMENT_DATA_CHANGED";
        public const string PAYMENT_PROCESSED_NOT_YET_CANT_REFUND = "PAYMENT_PROCESSED_NOT_YET_CANT_REFUND";
        public const string PAYMENT_REFUND_FOR_PAYMENT_EXISTING = "PAYMENT_REFUND_FOR_PAYMENT_EXISTING";

        #endregion Payment
    }
}
