// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace iChiba.ACC.Model
{
    public partial class ObjectGroup
    {
        public ObjectGroup()
        {
            Object = new HashSet<Object>();
        }

        public int Id { get; set; }
        public string GroupId { get; set; }
        public string GroupName { get; set; }
        public string Note { get; set; }
        public bool Active { get; set; }

        public virtual ICollection<Object> Object { get; set; }
    }
}