// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace iChiba.ACC.Model
{
    public partial class Statistic
    {
        public int Id { get; set; }
        public string StatisticId { get; set; }
        public string StatisticName { get; set; }
        public string Note { get; set; }
        public bool Active { get; set; }
    }
}