// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace iChiba.ACC.Model
{
    public partial class BankAccount
    {
        public int Id { get; set; }
        public string BankAccount1 { get; set; }
        public string BankName { get; set; }
        public string Branch { get; set; }
        public string Province { get; set; }
        public string Address { get; set; }
        public string Owner { get; set; }
        public string Note { get; set; }
        public bool Active { get; set; }
    }
}