// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace iChiba.ACC.Model
{
    public partial class Employee
    {
        public int Id { get; set; }
        public string EmployId { get; set; }
        public string EmployName { get; set; }
        public string Title { get; set; }
        public int? Department { get; set; }
        public int Gender { get; set; }
        public string TaxCode { get; set; }
        public string Identity { get; set; }
        public DateTime? DateOfIssue { get; set; }
        public string PlaceOfIssue { get; set; }
        public string Dependent { get; set; }
        public string Account { get; set; }
        public string Bank { get; set; }
        public string Note { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public bool Active { get; set; }

        public virtual Department DepartmentNavigation { get; set; }
    }
}