// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace iChiba.ACC.Model
{
    public partial class Object
    {
        public int Id { get; set; }
        public int Category { get; set; }
        public int Type { get; set; }
        public string ObjectName { get; set; }
        public string ObjectId { get; set; }
        public string Country { get; set; }
        public string Province { get; set; }
        public string District { get; set; }
        public string Commune { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string Website { get; set; }
        public string Fax { get; set; }
        public int ObjectGroup { get; set; }
        public string Identify { get; set; }
        public DateTime? IdIssuedDate { get; set; }
        public string IdIssuedBy { get; set; }
        public int Gender { get; set; }
        public string Email { get; set; }
        public string TaxCode { get; set; }
        public string Represent { get; set; }
        public int? RepGender { get; set; }
        public string RepTitle { get; set; }
        public string RepPhone { get; set; }
        public string RepMobile { get; set; }
        public string RepEmail { get; set; }
        public string BankNumber { get; set; }
        public string BankName { get; set; }
        public string BankBranch { get; set; }
        public string BankProvince { get; set; }
        public bool? Active { get; set; }

        public virtual ObjectGroup ObjectGroupNavigation { get; set; }
    }
}